# SearXNG settings

use_default_settings:
  engines:
    remove:
      - radio browser
      - ahmia
      - torch
      - yacy images
# Remove engines that don't exist in this SearXNG version to avoid warnings

general:
  debug: false
  instance_name: "SearXNG"

search:
  safe_search: 0
  formats:
    - json

server:
  secret_key: "dummy"
  port: 55510
  limiter: false
  image_proxy: false

ui:
  static_use_hash: true

enabled_plugins:
  - 'Hash plugin'
  - 'Self Informations'
  - 'Tracker URL remover'

engines:
  - name: radio browser
    engine: radio_browser
    disabled: true
    inactive: true
